/*
 * ----AUTHOR-----
 * NAMA : EFRONIUS PADUANSI
 * WEBSITE : myefronius.blogspot.com
 */
package pt.MDS;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import pt.MDS.koneksi;

public class addEmployee extends javax.swing.JDialog {

        Connection conn;
        Statement stat;
        ResultSet rs;
    
    /*Membuat ID Member Otomatis */
        private void IDMember(){
            try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/pt_mds", "root", "");
                Statement stat = conn.createStatement();
                ResultSet rs = stat.executeQuery("select max(right(idmember,3)) as no FROM employee ");

                    while(rs.next())
                    { if(rs.first() == false)
                        {      
                            idmember.setText("202102001");
                        }
                        else {
                               rs.last();
                               int auto_id = rs.getInt(1) + 1;
                               String no = String.valueOf(auto_id);
                               int noLong = no.length();
                                //MENGATUR jumlah 0
                                 for(int a=0;a<3-noLong;a++)
                                 { no = "0" + no;} 
                                 idmember.setText("202102" + no);
                            }       
                    }    
                }catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        
         //Validasi Username agar user memasukkan huruf kecil
       public void usernameKarakter(KeyEvent d) {

            if (Character.isUpperCase(d.getKeyChar())) {
                d.consume();

                //Pesan dialog
                JOptionPane.showMessageDialog(null, "Enter lowercase only!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
               }
       
    public addEmployee(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        IDMember();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idmember = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbbLevel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1000, 670));

        jPanel1.setBackground(new java.awt.Color(46, 139, 87));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 100));

        title.setFont(new java.awt.Font("Carlito", 1, 22)); // NOI18N
        title.setText("PT. MITRA DUA SEHATI");

        title2.setFont(new java.awt.Font("Carlito", 1, 22)); // NOI18N
        title2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/register.png"))); // NOI18N
        title2.setText("Add Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(title)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Gayathri", 1, 26)); // NOI18N
        jLabel2.setText("Register Employee Account");

        jLabel8.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel8.setText("ID Member");

        jLabel10.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel10.setText("Fullname");

        jLabel11.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel11.setText("Username");

        jLabel12.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel12.setText("Password");

        idmember.setEditable(false);
        idmember.setFont(new java.awt.Font("Carlito", 1, 20)); // NOI18N

        fullname.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        fullname.setPreferredSize(new java.awt.Dimension(26, 35));

        username.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        username.setPreferredSize(new java.awt.Dimension(26, 35));
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });

        password1.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
        password1.setPreferredSize(new java.awt.Dimension(157, 35));

        password2.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
        password2.setPreferredSize(new java.awt.Dimension(157, 35));
        password2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                password2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password2KeyTyped(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Carlito", 1, 20)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel13.setText("Retype Password");

        jLabel14.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel14.setText("Level");

        cbbLevel.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
        cbbLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Level--", "Admin", "Employee", "Manager" }));

        jLabel1.setForeground(java.awt.Color.green);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(38, 38, 38)
                                .addComponent(idmember, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(password2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                .addComponent(cbbLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idmember, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel8))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(cbbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped

        usernameKarakter(evt);
    }//GEN-LAST:event_usernameKeyTyped

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        //Menentukan panjang password
        int pjgPassword = password1.getText().length();
         //Validasi semua form
          try{
                if(fullname.getText().equals("")){
                      JOptionPane.showMessageDialog(this, "Field tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                else if(username.getText().toLowerCase().equals("")){
                      JOptionPane.showMessageDialog(this, "Field tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                else if(password1.getText().equals("")){
                      JOptionPane.showMessageDialog(this, "Field tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                else if(password2.getText().equals("")){
                      JOptionPane.showMessageDialog(this, "Field tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
                     
                }
                else if(pjgPassword <8){
                      JOptionPane.showMessageDialog(this, "Register Gagal!. Panjang Password Minimal 8 Karakter!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                
                else{
                    
                     //Input ke dalam database
                    String sql="INSERT INTO employee VALUE('"+idmember.getText()+"', '"+fullname.getText()+"', '"+username.getText()+"', '"+password1.getText()+"', '"+password2.getText()+"', '"+cbbLevel.getSelectedItem()+"')";
                    java.sql.Connection conn=(Connection)koneksi.koneksi();
                    java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                    pst.execute();
                    
                    JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
                    fullname.setText("");
                    username.setText("");
                    password1.setText("");
                    password2.setText("");
                    cbbLevel.getSelectedItem().equals("--Select Level--");
                    jLabel1.setText("");
                    }
                
                } catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this, e.getMessage()); 
              
                }
                IDMember();
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void password2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password2KeyTyped
        
    }//GEN-LAST:event_password2KeyTyped

    private void password2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password2KeyReleased
       // Mengatur Konfirmasi password
         String Password1 = new String (password1.getText());
         String Password2 = new String (password2.getText());
         
         if(Password2.equals("")){
              jLabel1.setText("");
         }
         else if(Password1.equals(Password2)){
              jLabel1.setText("Password cocok");
              jLabel1.setForeground(Color.GREEN);
          }
          else {
              jLabel1.setText("Password tidak cocok");
              jLabel1.setForeground(Color.RED);
          }
    }//GEN-LAST:event_password2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addEmployee dialog = new addEmployee(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbbLevel;
    private javax.swing.JTextField fullname;
    private javax.swing.JTextField idmember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title2;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
