/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.MDS;

import java.awt.Color;
import java.awt.Component;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;
import javax.swing.plaf.RootPaneUI;

//Package SQL Connection
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pt.MDS.koneksi;
import pt.MDS.entitas;



/**
 *
 * @author efron
 */
public class dashboard extends javax.swing.JFrame {
    
    //Deklarasikan SQL Connection
     Connection conn = null;
     ResultSet rs = null;
     PreparedStatement pst = null;
     String username = entitas.getUsername();
     String fullname = entitas.getFullname();
     String idmember = entitas.getIdmember();
     String level = entitas.getLevel();
     

     //menampilkan data ke dalam table
     private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("JOB NO");
        model.addColumn("BL");
        model.addColumn("SN");
        model.addColumn("CN");
        model.addColumn("MKTG");
        
        try{
            int no=1;
            String sql = "SELECT * FROM tb_import";
            java.sql.Connection conn = (Connection)koneksi.koneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                 model.addRow(new Object[]{no++,res.getString(1), res.getString(2),res.getString(4),res.getString(7),res.getString(9)});
            }
             tblDashboard.setModel(model);
        } catch(Exception e){
            
        }
        
     }
     

    //Membuat mode fullscreen
    static boolean maximixed = true;
    int xMouse;
    int yMouse;
    
    //Menampilkan waktu sekarang
    private void setJam()
    {
        ActionListener listener = new ActionListener() 
        {

            @Override
            public void actionPerformed(ActionEvent evt) 
            {
                jam.setText(new DateAndTime().getWkt());
            }
        };
            new Timer(1000, listener).start();
    }
    
    //Menampilkan tanggal sekarang
    public void date()
    {
        Date ys= new Date();
        SimpleDateFormat s= new SimpleDateFormat("EE, dd-MM-yyyy");
        tanggal.setText(s.format(ys));
    }
    
   
   
    
    public dashboard() {
        initComponents();
        setJam();
        date();
        load_table();
        settingPanel.setVisible(false);
       
     
        
        //Memanggil Koneksi
        conn = koneksi.koneksi();
        String query = "SELECT idmember, fullname, username, level FROM employee WHERE idmember=?";
        
        try{
            pst = conn.prepareStatement(query);
            pst.setString(1, idmember);
            rs = pst.executeQuery();
            while(rs.next())
            {
                txtEntitasFullname.setText(rs.getString("fullname"));
                txtEntitasLevel.setText(rs.getString("level"));
                txtEntitasidmember.setText("ID : " + " " + idmember);
                loginAs.setText(rs.getString("fullname"));
                welcomeText.setText(rs.getString("fullname"));
            }
            
        }
        catch(Exception e)
        {
            
        }
        if(level.equals("Employee"))
            {
                mnAddUsers.setEnabled(false);
                addUsersText.setEnabled(false);
                totalExportPanel.setVisible(false);
                totalImportPanel.setVisible(false);
                mnAddUsers.setVisible(false);
                addUsersText.setVisible(false);
                mnViewData.setVisible(false);
                mnAccountReceivable.setVisible(false);
            }
        else if(level.equals("Manager"))
            {
                mnAdd.setVisible(false);
                addText.setVisible(false);
            }
        else
            {
                
            }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        mnSetting = new javax.swing.JLabel();
        settingPanel = new javax.swing.JPanel();
        mnProfileInfo = new javax.swing.JLabel();
        mnAbout = new javax.swing.JLabel();
        mnDashboard = new javax.swing.JLabel();
        dashboardText = new javax.swing.JLabel();
        mnViewData = new javax.swing.JLabel();
        exportImportText = new javax.swing.JLabel();
        accountReceivableText = new javax.swing.JLabel();
        mnAccountReceivable = new javax.swing.JLabel();
        mnAdd = new javax.swing.JLabel();
        addText = new javax.swing.JLabel();
        mnLogout = new javax.swing.JLabel();
        mnAddUsers = new javax.swing.JLabel();
        addUsersText = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        mnFullscreen = new javax.swing.JLabel();
        mnExit = new javax.swing.JLabel();
        loginAs = new javax.swing.JLabel();
        loginAs1 = new javax.swing.JLabel();
        loginAs2 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        totalExportPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exportSUM = new javax.swing.JLabel();
        totalImportPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        importSUM = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        welcomeText = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDashboard = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JLabel();
        title5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtEntitasFullname = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEntitasLevel = new javax.swing.JLabel();
        txtEntitasidmember = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 80));
        setMinimumSize(new java.awt.Dimension(1200, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1400, 800));

        bgPanel.setBackground(new java.awt.Color(230, 230, 250));
        bgPanel.setForeground(java.awt.Color.white);
        bgPanel.setPreferredSize(new java.awt.Dimension(1300, 768));

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setPreferredSize(new java.awt.Dimension(300, 600));

        mnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/baseline_settings.png"))); // NOI18N
        mnSetting.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mnSettingMouseDragged(evt);
            }
        });
        mnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSettingMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnSettingMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnSettingMouseEntered(evt);
            }
        });

        settingPanel.setBackground(new java.awt.Color(85, 69, 118));

        mnProfileInfo.setForeground(java.awt.Color.white);
        mnProfileInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/profile.png"))); // NOI18N

        mnAbout.setForeground(java.awt.Color.white);
        mnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/baseline_info.png"))); // NOI18N
        mnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAboutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mnProfileInfo)
                    .addComponent(mnAbout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mnProfileInfo)
                .addGap(18, 18, 18)
                .addComponent(mnAbout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/dashboard.png"))); // NOI18N
        mnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnDashboardMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnDashboardMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnDashboardMouseEntered(evt);
            }
        });

        dashboardText.setFont(new java.awt.Font("Carlito", 0, 15)); // NOI18N
        dashboardText.setForeground(java.awt.Color.white);

        mnViewData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/view.png"))); // NOI18N
        mnViewData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnViewDataMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnViewDataMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnViewDataMouseEntered(evt);
            }
        });

        exportImportText.setFont(new java.awt.Font("Carlito", 0, 15)); // NOI18N
        exportImportText.setForeground(java.awt.Color.white);

        accountReceivableText.setFont(new java.awt.Font("Carlito", 0, 15)); // NOI18N
        accountReceivableText.setForeground(java.awt.Color.white);

        mnAccountReceivable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/accounts.png"))); // NOI18N
        mnAccountReceivable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAccountReceivableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnAccountReceivableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnAccountReceivableMouseExited(evt);
            }
        });

        mnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/add data.png"))); // NOI18N
        mnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAddMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnAddMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnAddMouseEntered(evt);
            }
        });

        addText.setFont(new java.awt.Font("Carlito", 0, 15)); // NOI18N
        addText.setForeground(java.awt.Color.white);

        mnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/logout.png"))); // NOI18N
        mnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnLogoutMouseClicked(evt);
            }
        });

        mnAddUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/add users.png"))); // NOI18N
        mnAddUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAddUsersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnAddUsersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnAddUsersMouseEntered(evt);
            }
        });

        addUsersText.setFont(new java.awt.Font("Carlito", 0, 15)); // NOI18N
        addUsersText.setForeground(java.awt.Color.white);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mnDashboard)
                    .addComponent(dashboardText)
                    .addComponent(mnViewData)
                    .addComponent(exportImportText)
                    .addComponent(mnAccountReceivable)
                    .addComponent(accountReceivableText)
                    .addComponent(addText)
                    .addComponent(mnAdd)
                    .addComponent(mnAddUsers)
                    .addComponent(addUsersText))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(mnSetting)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnLogout)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(mnDashboard)
                .addGap(8, 8, 8)
                .addComponent(dashboardText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnViewData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportImportText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnAccountReceivable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountReceivableText)
                .addGap(18, 18, 18)
                .addComponent(mnAddUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addUsersText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(settingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mnSetting, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mnLogout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(60, 60, 60))
        );

        headerPanel.setBackground(new java.awt.Color(102, 0, 153));

        mnFullscreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/outline_fullscreen.png"))); // NOI18N
        mnFullscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnFullscreenMouseClicked(evt);
            }
        });

        mnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/outline_close.png"))); // NOI18N
        mnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnExitMouseClicked(evt);
            }
        });

        loginAs.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        loginAs.setForeground(java.awt.Color.white);
        loginAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/outline_account.png"))); // NOI18N
        loginAs.setText("Efron Paduansi");

        loginAs1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        loginAs1.setForeground(java.awt.Color.white);
        loginAs1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/chat.png"))); // NOI18N

        loginAs2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        loginAs2.setForeground(java.awt.Color.white);
        loginAs2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/notification.png"))); // NOI18N

        title1.setFont(new java.awt.Font("Carlito", 0, 15)); // NOI18N
        title1.setForeground(java.awt.Color.white);
        title1.setText("Forwading Management Application");

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        title.setFont(new java.awt.Font("Carlito", 1, 22)); // NOI18N
        title.setText("Dashboard");

        tanggal.setFont(new java.awt.Font("Carlito", 1, 15)); // NOI18N
        tanggal.setText("Tanggal");

        jam.setFont(new java.awt.Font("Carlito", 1, 15)); // NOI18N
        jam.setText("Jam");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        title4.setFont(new java.awt.Font("Carlito", 1, 17)); // NOI18N
        title4.setForeground(java.awt.Color.white);
        title4.setText("PT. MITRA DUA SEHATI");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginAs1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginAs2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginAs, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnFullscreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnExit)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(title1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerPanelLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(title4)
                    .addContainerGap(1057, Short.MAX_VALUE)))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mnFullscreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginAs, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginAs2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginAs1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerPanelLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        totalExportPanel.setBackground(new java.awt.Color(189, 25, 107));
        totalExportPanel.setPreferredSize(new java.awt.Dimension(250, 250));

        jPanel5.setBackground(new java.awt.Color(86, 21, 102));

        jLabel1.setFont(new java.awt.Font("Carlito", 1, 22)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/leaderboard.png"))); // NOI18N
        jLabel1.setText("EXPORT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        exportSUM.setFont(new java.awt.Font("Carlito", 1, 36)); // NOI18N
        exportSUM.setForeground(java.awt.Color.white);
        exportSUM.setText("12, 345");

        javax.swing.GroupLayout totalExportPanelLayout = new javax.swing.GroupLayout(totalExportPanel);
        totalExportPanel.setLayout(totalExportPanelLayout);
        totalExportPanelLayout.setHorizontalGroup(
            totalExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(totalExportPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(exportSUM, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        totalExportPanelLayout.setVerticalGroup(
            totalExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalExportPanelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(exportSUM, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        totalImportPanel.setBackground(new java.awt.Color(189, 25, 107));
        totalImportPanel.setPreferredSize(new java.awt.Dimension(250, 250));

        jPanel6.setBackground(new java.awt.Color(86, 21, 102));

        jLabel2.setFont(new java.awt.Font("Carlito", 1, 22)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/leaderboard.png"))); // NOI18N
        jLabel2.setText("IMPORT");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        importSUM.setFont(new java.awt.Font("Carlito", 1, 36)); // NOI18N
        importSUM.setForeground(java.awt.Color.white);
        importSUM.setText("12, 345");

        javax.swing.GroupLayout totalImportPanelLayout = new javax.swing.GroupLayout(totalImportPanel);
        totalImportPanel.setLayout(totalImportPanelLayout);
        totalImportPanelLayout.setHorizontalGroup(
            totalImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalImportPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(importSUM, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        totalImportPanelLayout.setVerticalGroup(
            totalImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalImportPanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(importSUM, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(227, 27, 83));
        jPanel4.setForeground(new java.awt.Color(225, 46, 120));
        jPanel4.setPreferredSize(new java.awt.Dimension(390, 250));

        jPanel10.setBackground(new java.awt.Color(86, 21, 102));

        jLabel6.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Welcome Back");

        welcomeText.setFont(new java.awt.Font("Carlito", 0, 22)); // NOI18N
        welcomeText.setForeground(java.awt.Color.yellow);
        welcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeText.setText("Fullname");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(welcomeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeText)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 145, Short.MAX_VALUE))
        );

        jPanel7.setPreferredSize(new java.awt.Dimension(920, 200));

        tblDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NO", "JOB NO", "BL", "SN", "CN", "MKTG"
            }
        ));
        jScrollPane1.setViewportView(tblDashboard);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(85, 69, 118));
        jPanel8.setPreferredSize(new java.awt.Dimension(920, 38));

        title2.setFont(new java.awt.Font("Carlito", 1, 22)); // NOI18N
        title2.setForeground(java.awt.Color.white);
        title2.setText("Last transaction...");

        btnRefresh.setFont(new java.awt.Font("Carlito", 0, 20)); // NOI18N
        btnRefresh.setForeground(java.awt.Color.white);
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/refreshWhite1.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });

        title5.setFont(new java.awt.Font("Carlito", 0, 20)); // NOI18N
        title5.setForeground(java.awt.Color.white);
        title5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/search.png"))); // NOI18N
        title5.setText("Search");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(90, 90, 90)
                .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title2)
                    .addComponent(title5)
                    .addComponent(btnRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(92, 17, 217));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel9.setPreferredSize(new java.awt.Dimension(400, 768));

        jLabel5.setFont(new java.awt.Font("Gayathri", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PT/MDS/assets/account.png"))); // NOI18N

        txtEntitasFullname.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        txtEntitasFullname.setForeground(java.awt.Color.white);
        txtEntitasFullname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEntitasFullname.setText("Efron Paduansi");
        txtEntitasFullname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/facebook.png"))); // NOI18N

        txtEntitasLevel.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        txtEntitasLevel.setForeground(java.awt.Color.white);
        txtEntitasLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEntitasLevel.setText("Admin");

        txtEntitasidmember.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        txtEntitasidmember.setForeground(java.awt.Color.white);
        txtEntitasidmember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEntitasidmember.setText("ID : 1234567890");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/email.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEntitasidmember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEntitasLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEntitasFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel5)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEntitasFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEntitasLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEntitasidmember)
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addComponent(totalExportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalImportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalExportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalImportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(211, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnExitMouseClicked
       //Exit system
       
       int jawab = JOptionPane.showOptionDialog(this, 
                    "Are you sure to exit?", 
                    "Confirm", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
    
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "The program will exit");
            System.exit(0);
            
        }
       
    }//GEN-LAST:event_mnExitMouseClicked

    private void mnFullscreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnFullscreenMouseClicked
       
        //Membuat tampilan Fullscreen
          if(maximixed){
            dashboard.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            dashboard.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximixed = false;
        } else {
            setExtendedState(JFrame.NORMAL);
            maximixed = true;
        }
        
        
    }//GEN-LAST:event_mnFullscreenMouseClicked

    private void mnSettingMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSettingMouseDragged
      
    }//GEN-LAST:event_mnSettingMouseDragged

    private void mnSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSettingMouseEntered
         settingPanel.setVisible(true);
    }//GEN-LAST:event_mnSettingMouseEntered

    private void mnSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSettingMouseClicked
         settingPanel.setVisible(false);
         bgPanel.setBackground(Color.decode("#e6e6fa"));
         
    }//GEN-LAST:event_mnSettingMouseClicked

    private void mnSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSettingMouseExited
         
    }//GEN-LAST:event_mnSettingMouseExited

    private void mnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDashboardMouseEntered
        dashboardText.setText("Dashboard");
        
    }//GEN-LAST:event_mnDashboardMouseEntered

    private void mnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDashboardMouseExited
       dashboardText.setText("");
       
    }//GEN-LAST:event_mnDashboardMouseExited

    private void mnViewDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnViewDataMouseEntered
        exportImportText.setText("View Data");
    }//GEN-LAST:event_mnViewDataMouseEntered

    private void mnViewDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnViewDataMouseExited
        exportImportText.setText("");
    }//GEN-LAST:event_mnViewDataMouseExited

    private void mnAccountReceivableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAccountReceivableMouseEntered
       accountReceivableText.setText("Accounts");
       
    }//GEN-LAST:event_mnAccountReceivableMouseEntered

    private void mnAccountReceivableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAccountReceivableMouseExited
        accountReceivableText.setText("");
    }//GEN-LAST:event_mnAccountReceivableMouseExited

    private void mnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAboutMouseClicked
       settingPanel.setVisible(false);
      new about(this, rootPaneCheckingEnabled).show(); 
    }//GEN-LAST:event_mnAboutMouseClicked

    private void mnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAddMouseExited
      addText.setText("");
     
    }//GEN-LAST:event_mnAddMouseExited

    private void mnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAddMouseEntered
        addText.setText("Add data");
      
    }//GEN-LAST:event_mnAddMouseEntered

    private void mnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAddMouseClicked
        new EI_JDialog(this, rootPaneCheckingEnabled).show(); 
       
        bgPanel.setBackground(Color.GRAY);
        this.dispose();
       

    }//GEN-LAST:event_mnAddMouseClicked

    private void mnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDashboardMouseClicked
       bgPanel.setBackground(Color.decode("#e6e6fa"));
        
    }//GEN-LAST:event_mnDashboardMouseClicked

    private void mnViewDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnViewDataMouseClicked
       bgPanel.setBackground(Color.decode("#e6e6fa"));
      new DialogViewData(this, rootPaneCheckingEnabled).show(); 
        this.dispose();
       
       
        
    }//GEN-LAST:event_mnViewDataMouseClicked

    private void mnAccountReceivableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAccountReceivableMouseClicked
       bgPanel.setBackground(Color.decode("#e6e6fa"));
        new EmployeeData(this, rootPaneCheckingEnabled).show(); 
        
    }//GEN-LAST:event_mnAccountReceivableMouseClicked

    private void mnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnLogoutMouseClicked
         int jawab = JOptionPane.showOptionDialog(this, 
                    "Are you sure to Logout?", 
                    "Confirm", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
    
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Logout");
            new pt.MDS.login().setVisible(true);
            dispose();
        }
        
       
    }//GEN-LAST:event_mnLogoutMouseClicked

    private void mnAddUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAddUsersMouseClicked
       
        
        JOptionPane.showMessageDialog(this, "Fitur ini di isi oleh Manager dan Admin"); 
        // Membuka JDialog Addempolyee
         new addEmployee(this, rootPaneCheckingEnabled).show(); 
    }//GEN-LAST:event_mnAddUsersMouseClicked

    private void mnAddUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAddUsersMouseExited
        addUsersText.setText("");
    }//GEN-LAST:event_mnAddUsersMouseExited

    private void mnAddUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAddUsersMouseEntered
       
        addUsersText.setText("Employee");
    }//GEN-LAST:event_mnAddUsersMouseEntered

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
       load_table();
    }//GEN-LAST:event_btnRefreshMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountReceivableText;
    private javax.swing.JLabel addText;
    private javax.swing.JLabel addUsersText;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel btnRefresh;
    private javax.swing.JLabel dashboardText;
    private javax.swing.JLabel exportImportText;
    private javax.swing.JLabel exportSUM;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel importSUM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jam;
    private javax.swing.JLabel loginAs;
    private javax.swing.JLabel loginAs1;
    private javax.swing.JLabel loginAs2;
    private javax.swing.JLabel mnAbout;
    private javax.swing.JLabel mnAccountReceivable;
    private javax.swing.JLabel mnAdd;
    private javax.swing.JLabel mnAddUsers;
    private javax.swing.JLabel mnDashboard;
    private javax.swing.JLabel mnExit;
    private javax.swing.JLabel mnFullscreen;
    private javax.swing.JLabel mnLogout;
    private javax.swing.JLabel mnProfileInfo;
    private javax.swing.JLabel mnSetting;
    private javax.swing.JLabel mnViewData;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTable tblDashboard;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JPanel totalExportPanel;
    private javax.swing.JPanel totalImportPanel;
    private javax.swing.JLabel txtEntitasFullname;
    private javax.swing.JLabel txtEntitasLevel;
    private javax.swing.JLabel txtEntitasidmember;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
