/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.MDS;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author efron
 */
public class importpage extends javax.swing.JFrame {

     private void jobNo(){
         try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/pt_mds", "root", "");
                Statement stat = conn.createStatement();
                ResultSet rs = stat.executeQuery("select max(right(job_no,3)) as no FROM tb_import ");

                    while(rs.next())
                    {
                            
                        if(rs.first() == false)
                        {
                            
                            txtJobNo.setText("MDS2021I-001");

                        }
                        else
                            {
                                rs.last();
                                int auto_id = rs.getInt(1) + 1;
                                String no = String.valueOf(auto_id);
                                int noLong = no.length();
                                //MENGATUR jumlah 0
                                 for(int a=0;a<3-noLong;a++)
                                 {
                                     no = "0" + no;
                                 }
                                 
                                 txtJobNo.setText("MDS-2021I" + no);

                            }       
                    }    
                }catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
    }
    
    private void bookingNumber(){
         try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/pt_mds", "root", "");
                Statement stat = conn.createStatement();
                ResultSet rs = stat.executeQuery("select max(right(BL,3)) as no FROM tb_import ");

                    while(rs.next())
                    {
                            
                        if(rs.first() == false)
                        {
                            
                            txtJobNo.setText("BK-001");

                        }
                        else
                            {
                                rs.last();
                                int auto_id = rs.getInt(1) + 1;
                                String no = String.valueOf(auto_id);
                                int noLong = no.length();
                                //MENGATUR jumlah 0
                                 for(int a=0;a<3-noLong;a++)
                                 {
                                     no = "0" + no;
                                 }
                                 
                                 txtBL.setText("BK-" + no);

                            }       
                    }    
                }catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
    }
    
     private void clear()
    {
        txtBL.setText("");
        txtShipper.setText("");
        txtShipperName.setText("");
        txtShipperAdd.setText("");
        txtConsignee.setText("");
        txtConsigneeName.setText("");
        txtConsigneeAddress.setText("");
        txtMarketing.setText("");
        txtVessel.setText("");
        txtPOL.setText("");
        txtPlaceDlv.setText("");
      
        txtGrossW.setText("");
        txtCo20.setText("");
        txtCo40.setText("");
        txtCo45.setText("");
        txtAgenCd.setText("");
        txtVoyage.setText("");
        txtPOD.setText("");
       
        txtNetW.setText("");
        txtPackages.setText("");
    }
    
    public importpage() {
        initComponents();
        cboConsignee.setEnabled(false);
        jobNo();
        bookingNumber();
        clear();
    }

    importpage(EI_JDialog aThis, boolean rootPaneCheckingEnabled) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        menusPanel = new javax.swing.JPanel();
        mnHome1 = new javax.swing.JLabel();
        mnSave = new javax.swing.JLabel();
        mnView = new javax.swing.JLabel();
        mnCompany = new javax.swing.JLabel();
        cboShipper = new javax.swing.JComboBox<>();
        cboConsignee = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtBL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtJobNo = new javax.swing.JTextField();
        txtShipper = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtShipperName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtShipperAdd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtConsignee = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtConsigneeName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtConsigneeAddress = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMarketing = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtVessel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPOL = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPlaceDlv = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rboCY = new javax.swing.JRadioButton();
        rboCFS = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        txtGrossW = new javax.swing.JTextField();
        BL11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCo20 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCo40 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCo45 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAgenCd = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtVoyage = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtPOD = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNetW = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtPackages = new javax.swing.JTextField();
        tglETD = new com.toedter.calendar.JDateChooser();
        tglETA = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 771));

        header.setBackground(new java.awt.Color(108, 49, 151));
        header.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        header.setPreferredSize(new java.awt.Dimension(1400, 100));

        title.setFont(new java.awt.Font("Carlito", 1, 32)); // NOI18N
        title.setForeground(java.awt.Color.white);
        title.setText("IMPORT FORM");

        title1.setFont(new java.awt.Font("Carlito", 1, 22)); // NOI18N
        title1.setForeground(java.awt.Color.white);
        title1.setText("PT. MITRA DUA SEHATI");

        menusPanel.setBackground(new java.awt.Color(72, 61, 139));

        mnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/dashboard.png"))); // NOI18N
        mnHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnHome1MouseClicked(evt);
            }
        });

        mnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/save.png"))); // NOI18N
        mnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSaveMouseClicked(evt);
            }
        });

        mnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/view.png"))); // NOI18N
        mnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnViewMouseClicked(evt);
            }
        });

        mnCompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/MDS/assets/company2.png"))); // NOI18N
        mnCompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnCompanyMouseClicked(evt);
            }
        });

        cboShipper.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        cboShipper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Shipper--", "PT. Lakin Kemas Global", "PT. Cikupa Megah Kencana", "PT. Kencana Mulia Plastikindo", "PT. Spectrum Unitek", "PT. Indocap", "PT. Eterniti" }));
        cboShipper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboShipperActionPerformed(evt);
            }
        });

        cboConsignee.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        cboConsignee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Consignee--" }));

        javax.swing.GroupLayout menusPanelLayout = new javax.swing.GroupLayout(menusPanel);
        menusPanel.setLayout(menusPanelLayout);
        menusPanelLayout.setHorizontalGroup(
            menusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(mnHome1)
                .addGap(23, 23, 23)
                .addComponent(mnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(mnCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mnView, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(cboShipper, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboConsignee, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );
        menusPanelLayout.setVerticalGroup(
            menusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusPanelLayout.createSequentialGroup()
                .addGroup(menusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnView, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menusPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboShipper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboConsignee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(519, 519, 519)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jLabel1.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel1.setText("Job No");

        txtBL.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtBL.setCaretColor(new java.awt.Color(72, 61, 139));
        txtBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBLActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel2.setText("B/L");

        txtJobNo.setFont(new java.awt.Font("Carlito", 1, 19)); // NOI18N
        txtJobNo.setForeground(java.awt.Color.red);
        txtJobNo.setCaretColor(new java.awt.Color(72, 61, 139));

        txtShipper.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtShipper.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel3.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel3.setText("Shipper");

        jLabel4.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel4.setText("Name");

        txtShipperName.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtShipperName.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel5.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel5.setText("Address");

        txtShipperAdd.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtShipperAdd.setCaretColor(new java.awt.Color(72, 61, 139));
        txtShipperAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShipperAddActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel6.setText("Consignee");

        txtConsignee.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtConsignee.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel7.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel7.setText("Name");

        txtConsigneeName.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtConsigneeName.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel9.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel9.setText("Address");

        txtConsigneeAddress.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtConsigneeAddress.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel21.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel21.setText("Marketing");

        txtMarketing.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtMarketing.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel11.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel11.setText("Vessel");

        txtVessel.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtVessel.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel8.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel8.setText("POL");

        txtPOL.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtPOL.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel13.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel13.setText("Place Dlv");

        txtPlaceDlv.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtPlaceDlv.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel14.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel14.setText("ETD");

        jLabel15.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel15.setText("CY / CFS");

        buttonGroup2.add(rboCY);
        rboCY.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
        rboCY.setText("CY");
        rboCY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboCYActionPerformed(evt);
            }
        });

        buttonGroup2.add(rboCFS);
        rboCFS.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
        rboCFS.setText("CFS");
        rboCFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboCFSActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel16.setText("Gross W");

        txtGrossW.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtGrossW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGrossW.setCaretColor(new java.awt.Color(72, 61, 139));
        txtGrossW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrossWActionPerformed(evt);
            }
        });

        BL11.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        BL11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BL11.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel17.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel17.setText("Container");

        txtCo20.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtCo20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCo20.setCaretColor(new java.awt.Color(72, 61, 139));
        txtCo20.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCo20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCo20ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel18.setText("20");

        txtCo40.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtCo40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCo40.setCaretColor(new java.awt.Color(72, 61, 139));
        txtCo40.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel19.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel19.setText("40");

        jLabel20.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel20.setText("45");

        txtCo45.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtCo45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCo45.setCaretColor(new java.awt.Color(72, 61, 139));
        txtCo45.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel10.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel10.setText("Agen Cd");

        txtAgenCd.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtAgenCd.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel23.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel23.setText("Voyage");

        txtVoyage.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtVoyage.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel24.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel24.setText("POD");

        txtPOD.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtPOD.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel25.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel25.setText("ETA");

        jLabel22.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel22.setText("Net W");

        txtNetW.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtNetW.setCaretColor(new java.awt.Color(72, 61, 139));

        jLabel26.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jLabel26.setText("Packages");

        txtPackages.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        txtPackages.setCaretColor(new java.awt.Color(72, 61, 139));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Carlito", 0, 16)); // NOI18N
        jMenuItem1.setText("New Form");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Carlito", 0, 16)); // NOI18N
        jMenuItem2.setText("New Import Form");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Carlito", 0, 16)); // NOI18N
        jMenuItem3.setText("Save");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Carlito", 0, 16)); // NOI18N
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Carlito", 0, 16)); // NOI18N
        jMenuItem5.setText("Undo");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Carlito", 0, 16)); // NOI18N
        jMenuItem6.setText("Redo");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Carlito", 0, 16)); // NOI18N
        jMenuItem7.setText("Back to Dashboard");
        jMenuItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem7MouseClicked(evt);
            }
        });
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenu3.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Carlito", 0, 16)); // NOI18N
        jMenuItem8.setText("About");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel9))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsigneeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsigneeName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtShipperAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsignee, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtShipperName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel15))
                                                .addGap(42, 42, 42)
                                                .addComponent(rboCY)
                                                .addGap(18, 18, 18)
                                                .addComponent(rboCFS))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(47, 47, 47)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCo20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtGrossW, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(42, 42, 42)
                                                        .addComponent(BL11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(44, 44, 44))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtPOL, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel21))
                                                .addGap(36, 36, 36)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtMarketing, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtVessel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(tglETD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtPlaceDlv, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))))
                                        .addGap(16, 16, 16)))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel26))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(txtCo40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(txtCo45, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel20)
                                .addGap(161, 161, 161))))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBL, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtShipper, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPackages, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(txtAgenCd, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(txtVoyage, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(txtPOD, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(txtNetW, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(tglETA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarketing, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel10)
                    .addComponent(txtAgenCd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtVessel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(txtVoyage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtPlaceDlv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(tglETA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(txtNetW, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tglETD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rboCY)
                                    .addComponent(rboCFS)
                                    .addComponent(jLabel15)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPackages, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtConsigneeName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16)
                                        .addComponent(BL11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtGrossW, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtConsigneeAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtCo20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCo40, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtCo45, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtShipper, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtPOL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(txtPOD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtShipperName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtShipperAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConsignee, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(139, 139, 139))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnHome1MouseClicked
        //Kembali ke halaman Dashboard
        new dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnHome1MouseClicked

    private void mnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSaveMouseClicked
        // Input data ke table import
        
        //Atur tampilan tangggal
        String tampilan = "dd-MM-yyyy";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggalETD = String.valueOf(fm.format(tglETD.getDate()));
        String tanggalETA = String.valueOf(fm.format(tglETA.getDate()));
        
        try
        {
            //validasi form
            if(txtJobNo.getText().equals(""))
            {
               JOptionPane.showMessageDialog(this, "Job No tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);  
            }
            else if(txtBL.getText().equals(""))
            {
                 JOptionPane.showMessageDialog(this, "BL tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                
            
            //Buat query ke database
            String sql = "INSERT INTO tb_import VALUES("
                    + "'"+txtJobNo.getText()+"', '"+txtBL.getText()+"', '"+txtShipper.getText()+"', '"+txtShipperName.getText()+"', '"+txtShipperAdd.getText()+"', "
                    + "'"+txtConsignee.getText()+"', '"+txtConsigneeName.getText()+"', '"+txtConsigneeAddress.getText()+"', '"+txtMarketing.getText()+"', "
                    + "'"+txtVessel.getText()+"', '"+txtPOL.getText()+"', '"+txtPlaceDlv.getText()+"', '"+tanggalETD+"', '"+rboCY.isSelected()+"',"
                    + " '"+rboCFS.isSelected()+"', '"+txtGrossW.getText()+"', '"+txtCo20.getText()+"', '"+txtCo40.getText()+"', '"+txtCo45.getText()+"', '"+txtAgenCd.getText()+"', "
                    + "'"+txtVoyage.getText()+"', '"+txtPOD.getText()+"', '"+tanggalETA+"', '"+txtNetW.getText()+"', '"+txtPackages.getText()+"')";
            
            //Eksekusi query
            java.sql.Connection conn = (Connection)koneksi.koneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            // eksekusi query dan simpan hasilnya di obj ResultSet
            pst.execute();
            
            //Pesan informasi berhasil
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            int jawab = JOptionPane.showOptionDialog(this, 
                    "Apakah anda ingin menambahkan data lagi?", 
                    "Confirm", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
    
              if(jawab == JOptionPane.YES_OPTION)
                {  
                    clear();
                }
        }
        catch(Exception e)
        {
//            JOptionPane.showMessageDialog(this, e.getMessage());
            JOptionPane.showMessageDialog(null, "Data Gagal di Simpan!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        jobNo();
        bookingNumber();
        
    }//GEN-LAST:event_mnSaveMouseClicked

    private void mnViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnViewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnViewMouseClicked

    private void mnCompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnCompanyMouseClicked

    }//GEN-LAST:event_mnCompanyMouseClicked

    private void txtBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBLActionPerformed

    private void txtShipperAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShipperAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShipperAddActionPerformed

    private void rboCYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboCYActionPerformed
       
        if(rboCY.isSelected()){
            txtPackages.setEnabled(true);
            txtCo20.setEnabled(false);
            txtCo40.setEnabled(false);
            txtCo45.setEnabled(false);
        }
    }//GEN-LAST:event_rboCYActionPerformed

    private void txtCo20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCo20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCo20ActionPerformed

    private void txtGrossWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrossWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrossWActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void rboCFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboCFSActionPerformed
        
        if( rboCFS.isSelected()){
            txtPackages.setEnabled(false);
            txtCo20.setEnabled(true);
            txtCo40.setEnabled(true);
            txtCo45.setEnabled(true);
        }
    }//GEN-LAST:event_rboCFSActionPerformed

    private void cboShipperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboShipperActionPerformed
        cboConsignee.setEnabled(true);
        if( cboShipper.getSelectedItem().equals("--Select Shipper--"))
            {
                cboConsignee.setEnabled(false);
                txtShipper.setText("");
                txtShipperName.setText("");
                txtShipperAdd.setText("");
            }
        
        else if( cboShipper.getSelectedItem().equals("PT. Lakin Kemas Global"))
                {
                    txtShipper.setText("Tanjung Priok, JKT");
                    txtShipperName.setText("PT. Lakin Kemas Global");
                    txtShipperAdd.setText("Sukabumi-JKT Indonesia");
                }
        else if(cboShipper.getSelectedItem().equals("PT. Cikupa Megah Kencana"))
                {
                    txtShipper.setText("Tanjung Priok, JKT");
                    txtShipperName.setText("PT. Cikupa Megah Kencana");
                    txtShipperAdd.setText("Cikupa-Tangerang Indonesia");
                }
        else if( cboShipper.getSelectedItem().equals("PT. Kencana Mulia Plastikindo"))
                 {
                    txtShipper.setText("Tanjung Priok, JKT");
                    txtShipperName.setText("PT. Kencana Mulia Plastikindo");
                    txtShipperAdd.setText("BSD-Tangerang Selatan Indonesia");
                 }
        else if( cboShipper.getSelectedItem().equals("PT. Spectrum Unitek"))
                {
                     txtShipper.setText("Tanjung Priok, JKT");
                    txtShipperName.setText("PT. Spectrum Unitek");
                    txtShipperAdd.setText("BSD-Tangerang Selatan Indonesia");
                }
        else if( cboShipper.getSelectedItem().equals("PT. Indocap"))
                {
                    txtShipper.setText("Tanjung Priok, JKT");
                    txtShipperName.setText("PT. Indocap");
                    txtShipperAdd.setText("BSD-Tangerang Selatan Indonesia");  
                }
        else if( cboShipper.getSelectedItem().equals("PT. Eterniti"))
                {
                    txtShipper.setText("Tanjung Priok, JKT");
                    txtShipperName.setText("PT. Eterniti");
                    txtShipperAdd.setText("BSD-Tangerang Selatan Indonesia"); 
                }
        else
                {
                    txtShipper.setText("");
                    txtShipperName.setText("");
                    txtShipperAdd.setText("");
                    
                }
    }//GEN-LAST:event_cboShipperActionPerformed

    private void jMenuItem7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem7MouseClicked
     
      
    }//GEN-LAST:event_jMenuItem7MouseClicked

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
         new dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(importpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(importpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(importpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(importpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new importpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BL11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboConsignee;
    private javax.swing.JComboBox<String> cboShipper;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel menusPanel;
    private javax.swing.JLabel mnCompany;
    private javax.swing.JLabel mnHome1;
    private javax.swing.JLabel mnSave;
    private javax.swing.JLabel mnView;
    private javax.swing.JRadioButton rboCFS;
    private javax.swing.JRadioButton rboCY;
    private com.toedter.calendar.JDateChooser tglETA;
    private com.toedter.calendar.JDateChooser tglETD;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField txtAgenCd;
    private javax.swing.JTextField txtBL;
    private javax.swing.JTextField txtCo20;
    private javax.swing.JTextField txtCo40;
    private javax.swing.JTextField txtCo45;
    private javax.swing.JTextField txtConsignee;
    private javax.swing.JTextField txtConsigneeAddress;
    private javax.swing.JTextField txtConsigneeName;
    private javax.swing.JTextField txtGrossW;
    private javax.swing.JTextField txtJobNo;
    private javax.swing.JTextField txtMarketing;
    private javax.swing.JTextField txtNetW;
    private javax.swing.JTextField txtPOD;
    private javax.swing.JTextField txtPOL;
    private javax.swing.JTextField txtPackages;
    private javax.swing.JTextField txtPlaceDlv;
    private javax.swing.JTextField txtShipper;
    private javax.swing.JTextField txtShipperAdd;
    private javax.swing.JTextField txtShipperName;
    private javax.swing.JTextField txtVessel;
    private javax.swing.JTextField txtVoyage;
    // End of variables declaration//GEN-END:variables
}
